version: '3'
services:
  db:
    image: postgres:9.6.9-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "80:3000"
    depends_on:
      - db
volumes:
  pgdata: